import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Bio from '../components/bio/Bio'

import Post from '../components/Post'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Bio
          headshot="https://avatars.githubusercontent.com/u/94413896?v=4"
          name="Angela Yang"
          tagline="Fullstack Software Developer"
        />

        <ul className={styles.posts}>
          <li>
            <Post content="hi there" date="21/08/2022" />
          </li>

          <li>
            <Post
              content="Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
              date="21/08/2022"
            />
          </li>
          <li>
            <Post
              content="Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
              date="21/08/2022"
            />
          </li>
          <li>
            <Post
              content="Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
              date="21/08/2022"
            />
          </li>
        </ul>

        <form>
          <textarea className={styles.formContent}></textarea>
          <button className={styles.formButton}>Add new post</button>
        </form>
      </main>
    </div>
  )
}
